apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - image: picolas/backendlaravel-virtualisation
          imagePullPolicy: IfNotPresent
          name: back-end
          ports:
          - containerPort: 8080
      restartPolicy: Always