apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mysql
          imagePullPolicy: IfNotPresent
          name: db
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my_password
            - name: MYSQL_DATABASE
              value: my_database
            - name: MYSQL_USER
              value: my_user
            - name: MYSQL_PASSWORD
              value: my_password
      restartPolicy: Always