services:
  db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - esieevirtua

  backend:
    image: picolas/backendlaravel-virtualisation
    ports:
      - 8080
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - esieevirtua

  react:
    image: picolas/react-virtualisation
    ports:
      - 3000
    networks:
      - esieevirtua
networks:
    esieevirtua:
        driver: bridge