version: "3"

services:
  db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password

  backend:
    image: picolas/backendlaravel-virtualisation
    ports:
      - 80
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    links:
      - db

  react:
    image: picolas/react-virtualisation
    ports:
      - 3000
    links:
      - backend
      - db
