version: "3"

services:
  react:
    image: picolas/react-virtualisation
    ports:
      - "49159:3000"
    volumes:
      - ./react-app:/app
    depends_on:
      - backend
      - db

  backend:
    image: picolas/backendlaravel-virtualisation
    ports:
      - "49160:80"
    volumes:
      - ./laravel-app:/var/www/html/BackendLaravel
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "49161:3306"
