apiVersion: v1
kind: Pod
metadata:
  name: virtualisation
spec:
  containers:
  - name: reactapp
    image: picolas/react-virtualisation
    ports:
    - containerPort: 3000
  - name: laravelapp
    image: picolas/backendlaravel-virtualisation
    ports:
    - containerPort: 8080
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: my_password
    ports:
    - containerPort: 3306
