apiVersion: v1
kind: Service
metadata:
  name: load-balancer-react
  labels:
    app: reactapp
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31001
  selector:
    app: reactapp