apiVersion: v1
kind: Service
metadata:
  name: load-balancer-laravel
  labels:
    app: laravelapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31002
  selector:
    app: laravelapp