apiVersion: v1
kind: Service
metadata:
  name: laravelapp-service
spec:
  type: NodePort
  selector:
    name: laravelapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31002
