apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  type: NodePort
  selector:
    name: reactapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31001
      protocol: TCP
    
